# SELECT COUNT(*)
# FROM ANIMAL_INS;

# -- COUNT 안에 DISTINCT를 넣는 것이 핵심!
# SELECT COUNT(DISTINCT NAME)
# FROM ANIMAL_INS;

# SELECT ANIMAL_ID
# FROM ANIMAL_INS
# WHERE NAME IS NULL
# ORDER BY ANIMAL_ID;

# SELECT ANIMAL_TYPE, IFNULL(NAME, 'No name'), SEX_UPON_INTAKE
# FROM ANIMAL_INS
# ORDER BY ANIMAL_ID;